In [1]:
import numpy as np
import pandas as pd

# Numpy

Question 1


In [2]:
np.random.seed(11)
y=np.zeros((10,10)) 
z=np.random.choice(6,3)
np.put(y[2],z,np.random.choice(10,3))
y

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [7., 1., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Question 2

In [3]:
x = np.zeros((4,4))
x[::2,1::2] = 1
x[1::2, ::2] = 1
x

array([[0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

Question 3, Part 1: Numpy Broadcasting

In [4]:
x = np.zeros((6,6))
x = x+np.arange(1,7)
y = np.arange(1,7).reshape(6,1)
z = x*y
z

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 2.,  4.,  6.,  8., 10., 12.],
       [ 3.,  6.,  9., 12., 15., 18.],
       [ 4.,  8., 12., 16., 20., 24.],
       [ 5., 10., 15., 20., 25., 30.],
       [ 6., 12., 18., 24., 30., 36.]])

Question 3
Part 2, For loops

In [5]:
for i in range(0,6):
    for j in range(0,6):
        x[i][j]=(i+1)*(j+1)
print (x)

[[ 1.  2.  3.  4.  5.  6.]
 [ 2.  4.  6.  8. 10. 12.]
 [ 3.  6.  9. 12. 15. 18.]
 [ 4.  8. 12. 16. 20. 24.]
 [ 5. 10. 15. 20. 25. 30.]
 [ 6. 12. 18. 24. 30. 36.]]


# Pandas

Question 1

In [6]:
data = np.random.randint(0,1000,size = (26,1))
x = pd.DataFrame(data, columns = ['Random Numbers'], index = list('abcdefghijklmnopqrstuvwxyz'))
x.head()

Random Numbers
a             583
b             850
c             792
d             621
e             604

Question 2

In [7]:
data = {'Class 1': ['1', '2', '3', '4', '7', '11'], 'Class 2': ['4', '5', '6', '9', '7', '0'], 'Class 3': ['7', '5', '8', '12', '1', '11']}
df = pd.DataFrame(data, columns = ['Class 1', 'Class 2', 'Class 3'])
df_copy = df                                     #for resuing in question 3, part 3
series = df.iloc[::, :1:1].squeeze()
series


0     1
1     2
2     3
3     4
4     7
5    11
Name: Class 1, dtype: object

Question 3, Part 1

In [8]:
x = df.loc[ : , df_copy.columns != 'Class 3']
x

Class 1 Class 2
0       1       4
1       2       5
2       3       6
3       4       9
4       7       7
5      11       0

Question 3, Part 2

In [9]:
df = df.drop(index = df.iloc[:3].index)
df

Class 1 Class 2 Class 3
3       4       9      12
4       7       7       1
5      11       0      11

Question 3, Part 3

In [10]:
df = df_copy.drop(index = df.iloc[3:].index)
df

Class 1 Class 2 Class 3
0       1       4       7
1       2       5       5
2       3       6       8
3       4       9      12
4       7       7       1
5      11       0      11

Question 4

In [11]:
p1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
p2 = pd.Series([8, 9, 10, 11, 12, 7, 6, 5, 4, 3])
x = np.sum([(i*i) for i in p1])
y = np.sum([(j*j) for j in p2])
z = -1*np.sum([[2*i*j for (i,j) in zip(p1,p2)]])
Euclidean_distance = np.sqrt(np.sum(x+y+z))
Euclidean_distance


18.16590212458495

Question 5, Part 1

In [49]:
np.random.seed(42)
data = np.random.randint(1,100, size = (10,4))
df = pd.DataFrame(data, index = list('abcdefghij'), columns = list('pqrs'))
df

p   q   r   s
a  52  93  15  72
b  61  21  83  87
c  75  75  88  24
d   3  22  53   2
e  88  30  38   2
f  64  60  21  33
g  76  58  22  89
h  49  91  59  42
i  92  60  80  15
j  62  62  47  62

Question 5, Part 2

In [50]:
nearest_rows = []
nearest_distance = []

# iterate rows.
for i, row in df.iterrows():
    curr = row
    rest = df.drop(i)
    e_dists = {}  # init dict to store euclidean dists for current row.
    # iterate rest of rows for current row
    for j, contestant in rest.iterrows():
        # compute euclidean dist and update e_dists
        e_dists.update({j: round(np.linalg.norm(curr.values - contestant.values))})
    # update nearest row to current row and the distance value
    nearest_rows.append(max(e_dists, key=e_dists.get))
    nearest_distance.append(max(e_dists.values()))

df['nearest_row'] = nearest_rows
df['dist'] = nearest_distance
df

p   q   r   s nearest_row  dist
a  52  93  15  72           d   117
b  61  21  83  87           d   107
c  75  75  88  24           d    98
d   3  22  53   2           g   123
e  88  30  38   2           a   103
f  64  60  21  33           b    91
g  76  58  22  89           d   123
h  49  91  59  42           d    92
i  92  60  80  15           a   101
j  62  62  47  62           d    93

Question 6

In [46]:
L = pd.Series(range(15))

def func(arr, sl=5, wl=5):
    num_of_strides = ((15-wl)//sl) + 1
    return np.array([arr[s:(s+wl)] for s in np.arange(0, 15, sl)[:num_of_strides]])

func(L, sl = 2, wl = 4)


array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

Question 7, Part 1

In [15]:
data = np.arange(20).reshape(4,5)
x = pd.DataFrame(data, columns=['a', 'b', 'c', 'd', 'e'])
x


a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

Question 7, Part 2

In [16]:
df1 = x.reindex(columns=['c', 'b', 'a', 'd', 'e'])
df1



c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19

Question 7, Part 3

In [17]:
def switch_columns(x, col1=None, col2=None):
    colnames = x.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    x=x[colnames]
    return x

df1 = switch_columns(x, 'a', 'c')
print (df1)

    c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19


Question 7, Part 4

In [18]:
x.iloc[::, ::-1]

e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

Question 8

In [19]:
x = pd.Series(np.random.randint(1,10,10), pd.date_range('2021-01-01', periods=10, freq='W-SAT'))
x


2021-01-02    3
2021-01-09    7
2021-01-16    4
2021-01-23    9
2021-01-30    3
2021-02-06    5
2021-02-13    3
2021-02-20    7
2021-02-27    5
2021-03-06    9
Freq: W-SAT, dtype: int64

Question 9, Part 1

In [20]:
x = pd.Series([1,10,3, np.NaN], index = pd.to_datetime(['2021-01-01', '2021-01-03', '2021-01-06', '2021-01-08']))
x

2021-01-01     1.0
2021-01-03    10.0
2021-01-06     3.0
2021-01-08     NaN
dtype: float64

Question 9, Part 2

In [21]:
x = x.resample('D').ffill()
x["2021-01-08"] = 3.0
x

2021-01-01     1.0
2021-01-02     1.0
2021-01-03    10.0
2021-01-04    10.0
2021-01-05    10.0
2021-01-06     3.0
2021-01-07     3.0
2021-01-08     3.0
Freq: D, dtype: float64

Question 10, Part 1

In [22]:
np.random.seed(100)
df = pd.DataFrame({'Fruit': ['apple', 'banana', 'orange'] * 3,
                   'Taste': np.random.rand(9),
                   'Price': np.random.randint(0, 15, 9)})
df

Fruit     Taste  Price
0   apple  0.543405      8
1  banana  0.278369      4
2  orange  0.424518     11
3   apple  0.844776     12
4  banana  0.004719     10
5  orange  0.121569      0
6   apple  0.670749     11
7  banana  0.825853      9
8  orange  0.136707     13

Question 10, Part 2

In [23]:
df1 = df['Taste'].groupby(df['Fruit'])
df1
df1.get_group('banana').sort_values().iloc[1]

0.27836938509379616

Question 10, Part 3

In [24]:
x = df.groupby('Fruit', as_index = False)['Price'].mean()
x

Fruit      Price
0   apple  10.333333
1  banana   7.666667
2  orange   8.000000