In [1]:
import numpy as np

# 1. Create NumPy Arrays

In [2]:
#Question 1 

x=np.array([[1,2,3],[4,5,6]])
x
#Alternatively, 
#x = [[1,2,3],[4,5,6]]   #Consider a list
#np.array(x)             #Converting the list to array


array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
#Question 2
arr = np.arange(1,7).reshape(3,2)
arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
#Question 3
x = np.arange(2,101,2).mean()
x

#Alternatively,
#x =np.mean(np.arange(2,101,2))

51.0

In [5]:
#Question 4
np.random.seed(1)
y = np.random.random((3, 3, 3)).min()
y1 = np.random.random((3, 3, 3)).max()
y,y1


(0.00011437481734488664, 0.9888610889064947)

In [6]:
#Question 5
arr = np.arange(10,22).reshape(3,4)
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [7]:
#Question 6
arr1 = np.arange(5,33,3)                             
arr1

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [8]:
#Question 7
arr2 = np.random.random((10,10))
mem_size = arr2.size*arr2.itemsize
mem_size
#Alternatively
#arr3=np.random.randint(100, size=(10,10)).nbytes
#print(arr3)

800

In [9]:
#Question 8
arr3 = np.random.random(10)
arr3[4] = 5
arr3

array([0.25232574, 0.74382585, 0.19542948, 0.58135893, 5.        ,
       0.8468288 , 0.23984776, 0.49376971, 0.61995572, 0.8289809 ])

In [10]:
#Question 9
arr4 = np.arange(10,50)
arr4[::-1]

#Alternatively
#arr5=np.flip(np.arange(10,50,1))


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [11]:
#Question 10
np.random.seed(1000)
arr5 = np.random.rand(3,2)  
arr5

array([[0.65358959, 0.11500694],
       [0.95028286, 0.4821914 ],
       [0.87247454, 0.21233268]])

In [12]:
#Question 11
arr7 = np.full((5,5), np.arange(0,5,dtype=float))
arr7

#Alternatively
#arr6 = np.zeros((5,5))
#arr6 += np.arange(5)
#arr6

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [13]:
#Question 12
arr7 = np.ones((5,5))
x = np.pad(arr7, pad_width=1, mode='constant', constant_values=0)
x


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [14]:
#Question 13
arr8 = np.diag([1,2,3,4,5])
arr9 = np.roll(arr8,1,0)
arr9[0,4]=0
arr9


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [15]:
#Question 14
arr9 = np.ones((10,10))
arr9[1:-1, 1:-1] = 0
arr9


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [16]:
#Question 15
arr10 = np.random.uniform(0,10,10)

print(arr10 - arr10%1)
print(arr10 // 1)
print(np.floor(arr10))
print(arr10.astype(int))
print(np.trunc(arr10))

[0. 3. 2. 8. 2. 7. 3. 1. 7. 0.]
[0. 3. 2. 8. 2. 7. 3. 1. 7. 0.]
[0. 3. 2. 8. 2. 7. 3. 1. 7. 0.]
[0 3 2 8 2 7 3 1 7 0]
[0. 3. 2. 8. 2. 7. 3. 1. 7. 0.]


# 2. Operations on NumPy Arrays


In [17]:
#Question 1
x = [1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2]
num = 5
[i for i, v in enumerate(x) if v == 1][num-1]

8

In [18]:
#Question 2
x = np.arange(1,10)
y = np.split(x,[4,6,9])
y

[array([1, 2, 3, 4]), array([5, 6]), array([7, 8, 9]), array([], dtype=int32)]

In [19]:
#Question 3
x = np.arange(0,16).reshape(4,4)
np.hsplit(x,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [20]:
#Question 4
z1 = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(z1[:2, :2])
print(z1[1,0])

[[ 5 10]
 [20 25]]
20


In [21]:
#Question 5
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])
x,y
np.concatenate((x,y), axis = 1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [22]:
#Question 6
np.random.seed(1000)
y=np.random.randint(1,10,size=(5,3))
x=np.min(y,axis=1)/np.max(y,axis=1)
print(x)

[0.5        0.5        0.55555556 0.33333333 0.6       ]


In [23]:
#Question 7
np.random.seed(10)
x = np.random.random((5,5))
norm = (x-np.mean(x))/np.std(x)
norm

array([[ 0.96066644, -1.70233975,  0.47220685,  0.88077732, -0.00727213],
       [-0.9783923 , -1.07324334,  0.92238393, -1.17596469, -1.46253904],
       [ 0.65567875,  1.60665759, -1.76195895,  0.04128293,  1.10719933],
       [ 0.39726572,  0.78480942, -0.74039554,  1.48028113,  0.75933655],
       [ 0.14897173, -1.2715502 , -0.45136007,  0.61584836, -0.20835003]])

In [24]:
#Question 8
arr1 = np.arange(0,3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
np.concatenate((arr1, arr2, arr3), axis = 0)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
#Question 9
np.random.seed(1)
x=np.random.randint(1,100,20)
y=x[(x>=15)&(x<=55)]
y

array([38, 17, 26, 51, 21, 19, 29])

In [29]:
#Question 10
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c = np.arange(len(a)) [a==b]
c


array([1, 3, 5, 7])

In [27]:
#Question 11
x = np.arange(0,20)
x[x % 2 != 0] = -1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16,
       -1, 18, -1])

In [28]:
#Question 12
x = np.random.randint(0,10,(3,4,3,4))
sum1 = x.sum(axis=(-2,-1))
sum1

array([[68, 63, 53, 66],
       [65, 54, 65, 51],
       [50, 52, 48, 64]])